### PR TITLE
[cbindgen] Update to version 0.19.0

### PR DESCRIPTION
**Pull request by llewelld**

### CODE REVIEW

**Comment by Thaodan** [comment]
If you update the package the tag should be [packagename].

**Comment by rainemak** [comment]
> If you update the package the tag should be [packagename].

When doing packaging related changes [rpm], [spec], or [packaging] are just fine.

**Comment by Thaodan** [comment]
But it's not packaging it is updating the package.
Packaging changes are changed that just affect packaging and not the rest of the package.

**Comment by rainemak** [comment]
Continuing discussion from today's [community meeting](https://irclogs.sailfishos.org/meetings/sailfishos-meeting/2023/sailfishos-meeting.2023-08-31-06.59.log.html). I checked [dependencies](https://crates.io/crates/cbindgen/0.19.0/dependencies) (same as [this block](https://github.com/sailfishos-mirror/rust-cbindgen/blob/d9e490ce8b836194595bd30611253a7028059da2/Cargo.toml#L23)) listed for 0.19.0 are also met in local vendor submodules.  No need to touch to those submodules.

**Review by rainemak — APPROVED** [review]
Builds fine, vendor submodules are good, and finally esr71 builds fine against this version. Approving.

**Comment by llewelld** [comment]
Thanks for looking at this so carefully, for your comments and for the approval; I appreciate it. I've removed the draft status.

Following @Thaodan's comments, I am more than happy to change the commit title prefix (to, say `[cbindgen]`?) if this is preferred and helps make things clearer.

**Comment by Thaodan** [comment]
> Following @Thaodan's comments, I am more than happy to change the commit title prefix (to, say `[cbindgen]`?) if this is preferred and helps make things clearer.

Sounds good to me.

**Comment by llewelld** [comment]
Done.

**Pull request merged**
